name: movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^8.0.2
  flutter_native_splash: ^2.4.7
  introduction_screen: ^4.0.0
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  flutter_svg: ^2.2.3
  animated_toggle_switch: ^0.8.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/on_boarding_images/
    - assets/splash_images/
    - assets/translations/
