class AppStrings {
  AppStrings._();

  static const String onboardingTitle1 = 'onboarding_title_1';
  static const String onboardingBody1 = 'onboarding_body_1';
  static const String onboardingTitle2 = 'onboarding_title_2';
  static const String onboardingBody2 = 'onboarding_body_2';
  static const String onboardingTitle3 = 'onboarding_title_3';
  static const String onboardingBody3 = 'onboarding_body_3';
  static const String onboardingTitle4 = 'onboarding_title_4';
  static const String onboardingBody4 = 'onboarding_body_4';
  static const String onboardingTitle5 = 'onboarding_title_5';
  static const String onboardingBody5 = 'onboarding_body_5';
  static const String onboardingTitle6 = 'onboarding_title_6';
  static const String onboardingBody6 = '';
  static const String exploreNow = 'explore_now';
  static const String next = 'next';
  static const String back = 'back';
  static const String finish = 'finish';
  static const String email = 'email';
  static const String password = 'password';
  static const String forgetPassword = 'forget_password';
  static const String resetPassword = 'reset_password';
  static const String login = 'login';
  static const String createAccount = 'create_account';
  static const String loginWithGoogle = 'login_with_google';
  static const String donTHaveAccount = 'don\'t_have_account';
  static const String createOne = 'create_one';
  static const String or = 'or';
  static const String register = 'register';
  static const String name = 'name';
  static const String confirmPassword = 'confirm_password';
  static const String phoneNumber = 'phone_number';
  static const String alreadyHaveAccount = 'already_have_account';
  static const String avatar = 'avatar';
  static const String verifyEmail = 'verify_email';
  static const String watchList = 'watch_list';
  static const String history = 'history';
  static const String editProfile = 'edit_profile';
  static const String deleteAccount = 'delete_account';
  static const String updateData = 'update_data';
  static const String updateProfile = 'update_profile';
  static const String noItemsYet = 'no_items_yet';
  static const String emptyProfileMessage = 'empty_profile_message';
  static const String profile = 'profile';
  static const String exit = 'exit';
  static const String pickAvatar = 'pick_avatar';
}
